### ISSUE TITLE
咋用啊哥，没看懂

### ISSUE THREAD

**Issue by C147369** [2468785842/ImsTech#1]
![Uploading 屏幕截图 2024-10-17 203502.png…]()

**Comment by 2468785842** [comment]
你的图片没上传成功

**Comment by C147369** [comment]
![Screenshot_2024-10-23-08-21-53-816_com.github.android.jpg](https://github.com/user-attachments/assets/ff910573-afc0-471a-95ad-165c6a6a28bf)

这个配置和运行咋搞啊哥

**Comment by 2468785842** [comment]
> ![Screenshot_2024-10-23-08-21-53-816_com.github.android.jpg](https://private-user-images.githubusercontent.com/152271278/379054877-ff910573-afc0-471a-95ad-165c6a6a28bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDQwMjIsIm5iZiI6MTcyOTY0MzcyMiwicGF0aCI6Ii8xNTIyNzEyNzgvMzc5MDU0ODc3LWZmOTEwNTczLWFmYzAtNDcxYS05NWFkLTE2NWM2YTZhMjhiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwMDM1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDliZGM3ZjljOWQ4OTNlZjYyZDVkODgyMjdhNzkyYTYxYWQyYTA3ODAyMjBiZDA3N2ZhYjJiZjE3ZGMyOWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bzKnecBMGBMqEeUMnvZ9vQtGWLmw8YCWIb325yjm9e0)
> 
> 这个配置和运行咋搞啊哥

创建一个`.env`文件, 里面写你的账号密码,和浏览器路径
打开 `cmd` 按步骤输入三个命令,前两个命令会下载库,
之后 `npm run start` 运行
