### ISSUE TITLE
可以出一个发行版嘛

### ISSUE THREAD

**Issue by 1801841491** [2468785842/ImsTech#11]
作者大大，可以出一个发行版嘛

**Comment by 1801841491** [comment]
对的对的   麻烦啦！

**Comment by 2468785842** [comment]
我打包了个msi安装程序，因为包含chromium和node js体积很大

**Comment by 2468785842** [comment]
发行版可执行文件下载地址: https://github.com/2468785842/ImsTech/releases/latest/download/ims-tech-auto-1.0.0.Setup.exe

**Comment by 1801841491** [comment]
膜拜大佬
