### ISSUE TITLE
视频总是加载失败

### ISSUE THREAD

**Issue by biuwang90098** [2468785842/ImsTech#2]
![微信截图_20241023171218](https://github.com/user-attachments/assets/07b6e734-03bd-496e-bae3-591eb91b350d)
视频总是显示未知原因加载失败怎么办呀

**Comment by 2468785842** [comment]
![image](https://github.com/user-attachments/assets/8490e75a-609e-4eb8-883a-406a0331fcfc)
有可能是国开自己的的原因, 比如这里显示转码失败
你能上国开的课程页截个图吗?

**Comment by biuwang90098** [comment]
这是国开截图
![微信截图_20241023173511](https://github.com/user-attachments/assets/c5204fad-e4e4-42a9-bbb0-ac78584e06d7)

视频可以手动播放
![微信截图_20241023173532](https://github.com/user-attachments/assets/a4b92f5a-bcd1-473b-834c-2e655349ec8e)

**Comment by 2468785842** [comment]
把src/course/processor/OnlineVideoProc.ts里面的这段代码,删了试试
```typescript
    if (
      (await page
        .locator('activity-upload-resource-info-edit')
        .innerHTML({ timeout: 1000 })
        .catch(() => '')) == ''
    ) {
      console.log('未知原因加载失败: 跳过');
      return;
    }
```

**Comment by 2468785842** [comment]
已添加倍速, 你可以重新拉取下代码

**Comment by biuwang90098** [comment]
十分感谢！
