### ISSUE TITLE
【BUG】当有多个重复的syllabusName时任务异常结束

### ISSUE THREAD

**Issue by KingPrimes** [2468785842/ImsTech#5]
![image](https://github.com/user-attachments/assets/f6ab0fa2-7685-47bb-bda2-3a62d3450d4d)

**Comment by 2468785842** [comment]
能发下日志吗

**Comment by 2468785842** [comment]
可能是打错了
syllabusName: syllabus.moduleName,
应该是:
syllabusName: syllabus.syllabusName,
